name: "Conformer-Small-ASR-LibriSpeech"

model:
        sample_rate: 16000
        log_prediction: true
        load_weights_from_checkpoint: null
        ctc_reduction: mean_batch
        train_ds:
          manifest_filepath: "/data/4eickhof/data/LibriSpeech/train_clean_100.json,/data/4eickhof/data/LibriSpeech/train_clean_360.json,/data/4eickhof/data/LibriSpeech/train_other_500.json" 
          sample_rate: 16000
          batch_size: 16
          shuffle: true
          num_workers: 12
          pin_memory: true
          use_start_end_token: false
          trim_silence: false
          max_duration: 16.7
          min_duration: 0.1
          shuffle_n: 2048
          is_tarred: false
        validation_ds:
          manifest_filepath: "/data/4eickhof/data/LibriSpeech/dev_clean.json,/data/4eickhof/data/LibriSpeech/dev_other.json,/data/4eickhof/data/LibriSpeech/test_clean.json,/data/4eickhof/data/LibriSpeech/test_other.json" 
          sample_rate: 16000
          batch_size: 16
          shuffle: false
          num_workers: 8
          pin_memory: true
          use_start_end_token: false
          is_tarred: false
        test_ds:
          manifest_filepath: "/data/4eickhof/data/LibriSpeech/dev_clean.json,/data/4eickhof/data/LibriSpeech/dev_other.json,/data/4eickhof/data/LibriSpeech/test_clean.json,/data/4eickhof/data/LibriSpeech/test_other.json"
          sample_rate: 16000
          batch_size: 64
          shuffle: false
          num_workers: 8
          pin_memory: true
          use_start_end_token: false
          is_tarred: false
        tokenizer:
          dir: /data/4eickhof/repos/master_thesis_nemo/experiments/tokenizers/librispeech_tokenizer_wpe_v128/
          type: wpe
        preprocessor:
          _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
          sample_rate: 16000
          normalize: per_feature
          window_size: 0.025
          window_stride: 0.01
          window: hann
          features: 80
          n_fft: 512
          frame_splicing: 1
          dither: 1.0e-05
          pad_to: 0
          stft_conv: false
        spec_augment:
          _target_: nemo.collections.asr.modules.SpectrogramAugmentation
          freq_masks: 2
          time_masks: 5
          freq_width: 27
          time_width: 0.05
        encoder:
          _target_: nemo.collections.asr.modules.ConformerEncoder
          feat_in: 80
          feat_out: -1
          n_layers: 16
          d_model: 176
          subsampling: striding
          subsampling_factor: 4
          subsampling_conv_channels: 176
          ff_expansion_factor: 4
          self_attention_model: rel_pos
          n_heads: 4
          xscaling: true
          untie_biases: true
          pos_emb_max_len: 5000
          conv_kernel_size: 31
          dropout: 0.1
          dropout_emb: 0.0
          dropout_att: 0.1
        decoder:
          _target_: nemo.collections.asr.modules.ConvASRDecoder
          feat_in: 176
          num_classes: 128
          vocabulary:
          - '[PAD]'
          - '[UNK]'
          - '[CLS]'
          - '[SEP]'
          - '[MASK]'
          - ''''
          - a
          - b
          - c
          - d
          - e
          - f
          - g
          - h
          - i
          - j
          - k
          - l
          - m
          - 'n'
          - o
          - p
          - q
          - r
          - s
          - t
          - u
          - v
          - w
          - x
          - 'y'
          - z
          - '##r'
          - '##a'
          - '##y'
          - '##f'
          - '##i'
          - '##s'
          - '##h'
          - '##d'
          - '##e'
          - '##p'
          - '##o'
          - '##l'
          - '##c'
          - '##n'
          - '##m'
          - '##t'
          - '##g'
          - '##w'
          - '##v'
          - '##u'
          - '##x'
          - '##b'
          - '##k'
          - '##z'
          - '##q'
          - '##j'
          - th
          - the
          - '##er'
          - '##nd'
          - '##in'
          - '##ed'
          - '##ou'
          - '##at'
          - '##en'
          - and
          - '##or'
          - '##es'
          - to
          - of
          - '##on'
          - '##is'
          - '##ing'
          - '##ar'
          - '##it'
          - '##as'
          - '##an'
          - '##ll'
          - in
          - '##re'
          - wh
          - he
          - '##om'
          - be
          - ha
          - '##le'
          - '##ot'
          - '##ow'
          - '##ic'
          - '##ut'
          - it
          - '##ld'
          - that
          - sh
          - '##ly'
          - was
          - '##gh'
          - '##id'
          - '##se'
          - 'on'
          - '##ve'
          - '##et'
          - '##ent'
          - you
          - '##im'
          - '##st'
          - '##ce'
          - '##ith'
          - for
          - '##ir'
          - '##ion'
          - as
          - '##ay'
          - his
          - '##al'
          - with
          - '##ur'
          - st
          - '##ter'
          - her
          - '##ver'
          - '##ch'
          - re
          - '##ad'
          - '##ght'
          - an
        optim:
          name: adam
          lr: 2.0
          betas:
          - 0.9
          - 0.98
          weight_decay: 0
          sched:
            name: NoamAnnealing
            d_model: 176
            warmup_steps: 10000
            warmup_ratio: null
            min_lr: 1.0e-06
        target: nemo.collections.asr.models.ctc_bpe_models.EncDecCTCModelBPE

trainer:
  devices: [2,3] # number of GPUs, -1 would use all available GPUs
  num_nodes: 1
  max_epochs: 1000
  max_steps: null # computed at runtime if not set
  val_check_interval: 1.0 # Set to 0.25 to check 4 times per epoch, or an int for number of iterations
  accelerator: auto
  strategy: ddp
  accumulate_grad_batches: 8
  gradient_clip_val: 0.0
  precision: 32 # Should be set to 16 for O1 and O2 to enable the AMP.
  log_every_n_steps: 10  # Interval of logging.
  progress_bar_refresh_rate: 10
  resume_from_checkpoint: null # The path to a checkpoint file to continue the training, restores the whole state including the epoch, step, LR schedulers, apex, etc.
  num_sanity_val_steps: 0 # number of steps to perform validation steps for sanity check the validation process before starting the training, setting to 0 disables it
  check_val_every_n_epoch: 1 # number of evaluations on validation every n epochs
  sync_batchnorm: true
  enable_checkpointing: False  # Provided by exp_manager
  logger: false  # Provided by exp_manager

exp_manager:
  exp_dir: /data/4eickhof/repos/master_thesis_nemo/experiments
  name: ${name}
  create_tensorboard_logger: true
  create_checkpoint_callback: true
  checkpoint_callback_params:
    # in case of multiple validation sets, first one is used
    monitor: "val_loss"
    mode: "min"
    save_top_k: 5
    always_save_nemo: True # saves the checkpoints as nemo files instead of PTL checkpoints

  # you need to set these two to True to continue the training
  resume_if_exists: false
  resume_ignore_no_checkpoint: false

  # You may use this section to create a W&B logger
  create_wandb_logger: false
  wandb_logger_kwargs:
    name: null
    project: null
